src/AionFlux/AionFlux.Mvc/Controllers/FuncionarioController.cs
using Microsoft.AspNetCore.Mvc;
using PontoEletronico;

namespace AionFlux.Mvc.Controllers
{
    public class FuncionarioController : Controller
    {
        private AdminCartaoPonto AdminCartaoPonto;

        public FuncionarioController(AdminCartaoPonto adminCartaoPonto)
        {
            AdminCartaoPonto = adminCartaoPonto;
        }

        // GET: Funcionario
        public ActionResult Index()
        {
            var funcionarios = AdminCartaoPonto.funcionarios;
            return View(funcionarios);
        }

        // GET: Funcionario/Detalhes/5
        public ActionResult Detalhes(int id)
        {
            var funcionario = AdminCartaoPonto.funcionarios.Find(f => f.Id == id);
            return View(funcionario);
        }

        // GET: Funcionario/Criar
        public ActionResult Criar()
        {
            return View();
        }

        // POST: Funcionario/Criar

        //public int Id { get; set; }
        //public string Nome { get; set; }
        //public string CPF { get; set; }
        //public string RG { get; set; }
        //public string Telefone { get; set; }
        //public string Endereco { get; set; }
        //public string Email { get; set; }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Criar([Bind("Id,Nome,CPF,RG,Telefone,Endereco, Email")] Funcionario funcionario)
        {
            if (ModelState.IsValid)
            {
                AdminCartaoPonto.CadastrarFuncionario(funcionario);
                return RedirectToAction("Index");
            }
            return View(funcionario);
        }

        // GET: Funcionario/Editar/5
        public ActionResult Editar(int id)
        {
            var funcionario = AdminCartaoPonto.funcionarios.Find(f => f.Id == id);
            return View(funcionario);
        }

        // POST: Funcionario/Editar/5
        [HttpPost]
        public ActionResult Editar(int id, Funcionario novoFuncionario)
        {
            if (ModelState.IsValid)
            {
                AdminCartaoPonto.EditarFuncionario(id, novoFuncionario);
                return RedirectToAction("Index");
            }
            return View(novoFuncionario);
        }

        // GET: Funcionario/Excluir/5
        public ActionResult Excluir(int id)
        {
            var funcionario = AdminCartaoPonto.funcionarios.Find(f => f.Id == id);
            return View(funcionario);
        }

        // POST: Funcionario/Excluir/5
        [HttpPost, ActionName("Excluir")]
        public ActionResult ConfirmarExclusao(int id)
        {
            AdminCartaoPonto.RemoverFuncionario(id);
            return RedirectToAction("Index");
        }
    }
}

src/AionFlux/AionFlux.Mvc/Views/Funcionario/Criar.cshtml
@model PontoEletronico.Funcionario

@{
    ViewBag.Title = "Criar Funcionário";
}

<h2>Criar Funcionário</h2>

@using (Html.BeginForm("Criar","Funcionario"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Informações do Funcionário</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RG, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RG, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
       
        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar à Lista", "Index")
</div>

src/AionFlux/AionFlux.Mvc/Views/Funcionario/Index.cshtml
@model IEnumerable<PontoEletronico.Funcionario>

@{
    ViewBag.Title = "Funcionário";
}

<h2>Funcionários</h2>

<p>
    @Html.ActionLink("Novo Funcionário", "Criar")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { id = item.Id }) |
                @Html.ActionLink("Detalhes", "Detalhes", new { id = item.Id }) |
                @Html.ActionLink("Excluir", "Excluir", new { id = item.Id })
            </td>
        </tr>
    }
</table>